name: Trigger Target Workflow

on:
  push:
    tags:
      - '*'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Message
        run: |
          curl --request POST \
          --header "Authorization: token ${{ secrets.B2AI_REDCAP2RS_PAT }}" \
          --header "Accept: application/vnd.github.v3+json" \
          --url https://api.github.com/repos/Evan8456/b2ai-redcap2rs/actions/workflows/deploy.yml/dispatches \
          --data '{"ref":"main"}'